# Generated by Django 2.0.2 on 2018-08-18 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.SlugField(default=lab.models.increment_invoice_number, max_length=25, unique=True)),
                ('Name', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=2, unique=True)),
                ('availablity_status', models.CharField(choices=[('active', 'Active'), ('shutdown', 'Shutdown'), ('opensoon', 'Opening Soon')], default='available', max_length=13)),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Incharge', models.CharField(max_length=20)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Designation', models.CharField(max_length=15)),
                ('Joindate', models.DateField()),
                ('Mobile', models.BigIntegerField()),
                ('emp_branchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20, unique=True)),
                ('Code', models.SlugField(max_length=10, unique=True)),
                ('Referance', models.CharField(max_length=20)),
                ('Unit', models.CharField(max_length=10)),
                ('availablity_status', models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=13)),
                ('Rate', models.IntegerField()),
                ('GST', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TestTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(max_length=20, unique=True)),
                ('Username', models.CharField(max_length=20)),
                ('ResultValue', models.CharField(max_length=20)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Test')),
            ],
        ),
    ]
