# Generated by Django 2.0.2 on 2018-08-27 09:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('email_host', models.CharField(max_length=1024, verbose_name='EMAIL_HOST')),
                ('email_host_user', models.CharField(max_length=255, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='EMAIL_PORT')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='test',
            name='GST',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Addedby',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtaken',
            name='Remarks',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtaken',
            name='Today',
            field=models.DateField(default=datetime.date(2018, 8, 27)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^\\+?1?\\d{9,13}$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='test',
            name='Code',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='Rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testtaken',
            name='app_code',
            field=models.CharField(max_length=20),
        ),
    ]
